# Generated by Django 2.2.7 on 2019-11-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='n/a', max_length=255)),
                ('started', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(default='n/a', max_length=255)),
                ('serial', models.CharField(default='n/a', max_length=255)),
                ('mounted', models.BooleanField(default=False)),
            ],
        ),
    ]
