# Generated by Django 2.2.7 on 2019-11-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191112_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wipe_in_progress', models.BooleanField(default=False)),
            ],
        ),
    ]
