# Generated by Django 2.2.7 on 2019-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backgroundtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='backup_size',
            field=models.CharField(default='n/a', max_length=30),
        ),
    ]
