# Generated by Django 2.2.7 on 2019-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backupjob_backup_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskWipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='n/a', max_length=255)),
                ('celery_id', models.CharField(default='n/a', max_length=255)),
            ],
        ),
    ]
