# Generated by Django 2.2.7 on 2019-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_diskwipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskwipe',
            name='celery_status',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
