# Generated by Django 2.2.7 on 2019-11-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_diskwipe_celery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskwipe',
            name='celery_status',
        ),
    ]
