# Generated by Django 2.2.7 on 2019-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_diskwipe_celery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='celery_id',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
