# Generated by Django 2.2.7 on 2019-11-13 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backupjob_celery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskwipe',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
