# Generated by Django 2.2.7 on 2019-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diskwipe_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='n/a', max_length=255)),
                ('celery_id', models.CharField(default='n/a', max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(default='n/a', max_length=255)),
                ('serial', models.CharField(default='n/a', max_length=255)),
            ],
        ),
    ]
