# Generated by Django 2.2.7 on 2019-11-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_diskcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='n/a', max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('celery_id', models.CharField(default='n/a', max_length=255)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backupjob', to='core.BackupJob')),
            ],
        ),
    ]
