# Generated by Django 2.2.7 on 2019-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_virusscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='virus_scan_running',
            field=models.BooleanField(default=False),
        ),
    ]
