# Generated by Django 3.0.1 on 2019-12-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backupjob_virus_scan_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virusscan',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backupjobs', to='core.BackupJob'),
        ),
    ]
