# Generated by Django 3.0.1 on 2019-12-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191219_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='n/a', max_length=255)),
                ('celery_id', models.CharField(default='n/a', max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
